# Engine command goal
string command
string MOTION_START=start
string MOTION_STOP=stop
string MOTION_GENERATE=generate  # Generate path, but do not run

Trajectory trajectory

---
# result
bool result

string errorId
string FAILED_TO_PARAMETERIZE=FAILED_TO_PARAMETERIZE
string PLANNED_MOTION_COLLISION=PLANNED_MOTION_COLLISION
string INVALID_TRAJECTORY_MESSAGE=INVALID_TRAJECTORY_MESSAGE
string ENDPOINT_DOES_NOT_EXIST=ENDPOINT_DOES_NOT_EXIST
string CARTESIAN_INTERPOLATION_FAILED=CARTESIAN_INTERPOLATION_FAILED
string FINAL_POSE_NOT_WITHIN_TOLERANCE=FINAL_POSE_NOT_WITHIN_TOLERANCE
string CONTROLLER_NOT_FOLLOWING=CONTROLLER_NOT_FOLLOWING
string ZERO_G_ACTIVATED_DURING_TRAJECTORY=ZERO_G_ACTIVATED_DURING_TRAJECTORY
string PLANNED_JOINT_ACCEL_LIMIT=PLANNED_JOINT_ACCEL_LIMIT

TrajectoryAnalysis trajectory_analysis

int32 last_successful_waypoint
int32 HAVE_NOT_REACHED_FIRST_WAYPOINT=-1
int32 GENERAL_TRAJECTORY_FAILURE=-2

---
# feedback
MotionStatus status
